name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release PR or Release
        id: release_please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node
          package-name: 'room-card-minimalist'

      - name: Setup Node.js
        if: steps.release_please.outputs.release_created == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install
        if: steps.release_please.outputs.release_created == 'true'
        run: npm ci

      - name: Build
        if: steps.release_please.outputs.release_created == 'true'
        run: npm run build

      - name: Upload Release Artifacts
        if: steps.release_please.outputs.release_created == 'true'
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist/*.js'
          allowUpdates: true
          tag: ${{ steps.release_please.outputs.tag_name }}
